# Optional Lab: Python、NumPy 与向量化
本课程中使用的一些科学计算的简要介绍。特别是 NumPy 科学计算包及其在 Python 中的使用。

# 大纲
- [&nbsp;&nbsp;1.1 目标](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 有用的参考文献](#toc_40015_1.2)
- [2 Python and NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 向量](#toc_40015_3)
- [&nbsp;&nbsp;3.1 摘要](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy 数组](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 向量创建](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 向量运算](#toc_40015_3.4)
- [4 Matrices矩阵](#toc_40015_4)
- [&nbsp;&nbsp;4.1 摘要](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy 数组](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 矩阵创建](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 矩阵运算](#toc_40015_4.4)


In [20]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_1.1"></a>
## 1.1 目标
在本实验中，你将：
- 复习课程 1 中使用的 NumPy 和 Python 的特性。

<a name="toc_40015_1.2"></a>
## 1.2 有用的参考资料
- NumPy 文档，包括基础介绍： [NumPy.org](https://NumPy.org/doc/stable/)
- 一个具有挑战性的特性： [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_2"></a>
# 2 Python and NumPy <a name='Python and NumPy'></a>
Python 是我们在本课程中将要使用的编程语言。它有一组数值数据类型和算术运算。NumPy 是一个库，它扩展了 Python 的基本功能，增加了更丰富的数据集，包括更多的数值类型、向量、矩阵和许多矩阵函数。NumPy 和 Python 能够相当无缝地协同工作。Python 算术运算符适用于 NumPy 数据类型，并且许多 NumPy 函数将接受 Python 数据类型。


<a name="toc_40015_3"></a>
# 3 向量
<a name="toc_40015_3.1"></a>
## 3.1 摘要
<img align="right" src="../work/images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >向量，正如你在本课程中使用的那样，是有序的数字数组。在表示法中，向量用小写粗体字母表示，例如$\mathbf{x}$。向量的元素都是相同类型的。例如，向量不能同时包含字符和数字。数组中的元素数量通常被称为**维度**，尽管数学家可能更喜欢叫做**秩**。所示向量的维度为$n$。向量的元素可以通过索引来引用。在数学环境中，索引通常从 1 到$n$。在计算机科学和这些实验中，索引通常从 0 到$n - 1$。在表示法中，当单独引用向量的元素时，会在下标中指示索引，例如，向量$\mathbf{x}$的第$0$个元素是$x_0$。请注意，在这种情况下，$x$不是粗体。


<a name="toc_40015_3.2"></a>
## 3.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维数组，其中包含相同类型（数据类型）的元素。你可能马上就会注意到我们重载了 **维度** 这个术语。在上面，它是向量中元素的数量，在这里，维度指的是数组的索引数量。一维或 1-D 数组有一个索引。在课程 1 中，我们将向量表示为 NumPy 的 1-D 数组。

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]
 - 一维数组，形状为(n,)：n 个元素从[0]到[n - 1]进行索引。
 

<a name="toc_40015_3.3"></a>
## 3.3 向量创建


NumPy 中的数据创建例程通常有一个第一参数，它是一个shape对象。对于一维结果，这可以是单个值，或者是一个元组(n,m,...)，指定结果的形状。下面是使用这些例程创建向量的示例。

In [21]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.04997798 0.77390955 0.93782363 0.5792328 ], a shape = (4,), a data type = float64


一些数据创建例程不接受shape元组。

In [22]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.53516563 0.80204309 0.24814448 0.59096694], a shape = (4,), a data type = float64


值也可以手动指定。

In [23]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


这些都创建了一个具有四个元素的一维向量`a`。`a.shape`返回维度。在这里，我们看到`a.shape = (4,)`，表示一个具有四个元素的一维数组。

<a name="toc_40015_3.4"></a>
## 3.4 向量运算
让我们探索一些使用向量的运算。
<a name="toc_40015_3.4.1"></a>
### 3.4.1 Indexing
向量的元素可以通过索引和切片来访问。NumPy 提供了一套非常完整的索引和切片功能。在这里，我们将只探讨本课程所需的基础知识。 参考 [切片和索引](https://NumPy.org/doc/stable/reference/arrays.indexing.html) 获取更多详细信息。
**索引**意味着通过数组中元素的位置来引用该元素。<br/> 
**切片**意味着根据索引从数组中获取元素的子集。  
NumPy 从 0 开始索引，所以向量$\mathbf{a}$的第三个元素是`a[2]`。

In [24]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 切片
切片通过一组三个值（`起始值：结束值：步长`）创建一个索引数组。一个值的子集也是有效的。通过示例可以最好地解释其用法：

In [6]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 单向量操作
有许多有用的操作涉及对单个向量的操作。

In [7]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 向量逐元素操作
NumPy 的大多数算术、逻辑和比较运算也适用于向量。这些运算符基于元素逐个进行操作。例如:
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [8]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


当然，为了使这个正确地工作，向量必须具有相同的`size`：

In [9]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 标量向量运算
向量可以通过标量值进行**缩放**。标量值只是一个数字。该标量会与向量的所有元素相乘。

In [10]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 向量点积
点积是线性代数和 NumPy 的重要组成部分。在本课程中，点积这一运算被广泛使用，应该被充分理解。点积如下所示:

<img src="../work/images/C1_W2_Lab04_dot_notrans.gif" width=800> 

点积将两个向量中的值逐元素相乘，然后对结果求和。
向量点积要求两个向量的维度相同。

让我们在下面实现我们自己版本的点积：

**使用 for 循环**，实现一个函数，该函数返回两个向量的点积。给定输入$a$和$b$，函数应返回：
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
假设`a`和`b`的shape相同。

In [11]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [12]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


注意，点积预期会返回一个标量值。让我们使用`np.dot`尝试相同的操作。

In [40]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


在上文中，你会注意到一维的结果与我们的实现相匹配。

<a name="toc_40015_3.4.7"></a>
### 3.4.7 速度的需求：向量与for循环
我们使用了 NumPy 库，因为它提高了速度和内存效率。让我们来演示一下：

In [25]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 5.5580 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 1634.4080 ms 


因此，在这个例子中，向量化提供了很大的速度提升。这是因为 NumPy 更好地利用了底层硬件中可用的数据并行性。GPU 和现代 CPU 实现单指令多数据（SIMD）流水线，允许并行执行多个操作。这在机器学习中至关重要，因为数据集通常非常大。

<a name="toc_12345_3.4.8"></a>
### 3.4.8 课程 1 中的向量运算
向量和向量之间的操作在课程 1 中会频繁出现。原因如下：
- 接下来，我们的示例将存储在一个维度为(m,n)的数组`X_train`中。这将在上下文中进行更多解释，但在这里重要的是要注意它是一个二维数组或矩阵（请参阅下一节关于矩阵的内容）。
- `w`将是形状为(n,)的一维向量。
- 我们将通过遍历示例来执行操作，通过对 X 进行索引来单独提取每个示例进行处理。例如：`X[i]`
- `X[i]`返回一个形状为(n,)的一维向量值。因此，涉及`X[i]`的操作通常是向量与向量的操作。

这是一个有点冗长的解释，但是在执行向量运算时，对齐并理解操作数的形状很重要。

In [26]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 矩阵


<a name="toc_40015_4.1"></a>
## 4.1 摘要
矩阵是二维数组。矩阵的元素都是相同类型的。在表示法中，矩阵用大写粗体字母表示，例如$\mathbf{X}$。在这个以及其他实验中，`m`通常是行数，`n`是列数。矩阵的元素可以通过二维索引来引用。在数学设置中，索引中的数字通常从 1 到 n。在计算机科学和这些实验中，索引将从 0 到 n - 1。
<figure>
    <center> <img src="../work/images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> 通用矩阵表示法，第一个索引是行，第二个是列。 </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## 4.2 NumPy 数组

NumPy 的基本数据结构是可索引的 n 维*数组*，其中包含相同类型（`dtype`）的元素。前面已经介绍过这些内容。矩阵具有二维（2-D）索引 [m,n]。

在课程 1 中，二维矩阵用于保存训练数据。训练数据是由$m$个示例和$n$个特征组成的（m，n）数组。课程 1 不会直接对矩阵进行操作，而是通常将一个示例提取为向量并对其进行操作。下面你将回顾：
- 数据创建
- 切片和索引

<a name="toc_40015_4.3"></a>
## 4.3 矩阵创建
创建一维向量的相同函数也可以创建二维或 n 维数组。下面是一些例子。

下面，提供形状元组以获得二维结果。请注意 NumPy 如何使用括号表示每个维度。进一步注意，在打印时，NumPy 会每行打印一行。


In [27]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


人们也可以手动指定数据。维度使用额外的括号指定，与上面打印内容的格式相匹配。

In [43]:
# NumPy 中分配内存并使用用户指定的值填充的例程。
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 矩阵运算
让我们探索一些使用矩阵的运算。

<a name="toc_40015_4.4.1"></a>
### 4.4.1 索引


矩阵包含第二个索引。这两个索引描述[行，列]。访问可以返回一个元素或者一行/一列。请见下文：

In [46]:
#矩阵上的向量索引操作
a = np.arange(6).reshape(-1, 2)   #reshape重塑是创建矩阵的一种便捷方式。
print(f"a.shape: {a.shape}, \na= {a}")

#访问一个元素
print(f"\na[2,0].shape: {a[2, 0].shape}, a[2,0] = {a[2, 0]}, type(a[2,0]) = {type(a[2, 0])}访问一个元素会返回一个标量。\n")

#访问一行
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int64'>访问一个元素会返回一个标量。

a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


值得注意最后一个例子。仅指定行来访问矩阵将返回一个**一维向量**。

**Reshape**  
上一个示例使用了[重塑](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)来调整数组的形状。
`a = np.arange(6).reshape(-1, 2) `   
这段代码首先创建了一个包含六个元素的**一维向量**。然后，它使用`reshape`命令将该向量重塑为一个**二维**数组。可以这样写：  
`a = np.arange(6).reshape(3, 2) `  
要得到相同的 3 行 2 列数组。<br/> 
-1 参数告诉例程在给定数组大小和列数的情况下计算行数。


<a name="toc_40015_4.4.2"></a>
### 4.4.2 切片
切片通过一组三个值（`起始：结束：步长`）创建一个索引数组。值的子集也是有效的。最好通过示例来解释它的用法：

In [47]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## 恭喜！!
在这个实验室中，你掌握了课程 1 所需的 Python 和 NumPy 的特性。